Added exposed ports and reworked scripts.

diff --git a/docker/daemon b/docker/daemon
--- a/docker/daemon
+++ b/docker/daemon
@@ -1,10 +1,9 @@
 #!/usr/bin/env bash
 
 EXEC_DIR=`dirname $0`
-MODE=$1
 
-if [ "$MODE" = "start" ]; then
-    $( cd $EXEC_DIR; VERSION=$2 make daemon-start; )
-elif [ "$MODE" = "stop" ]; then
-    $( cd $EXEC_DIR; make daemon-stop; )
+if [ "$1" = "" ]; then
+    echo "ERROR: The 'daemon' script requires a version as a passed positional parameter."
+    exit 127
 fi
+cd $EXEC_DIR; VERSION=$1 make daemon-start
